apiVersion: v1
kind: Service
metadata:
  name: vip-honcho
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.250"
    metallb.universe.tf/allow-shared-ip: "metallb-shared-vip"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.250
  selector:
    app: honcho
  ports:
    - name: http
      port: 8000
      targetPort: 8000
